language: python
python:
  - 2.7
before_install:
  - pip freeze | xargs pip uninstall -y
install:
  - pip install -U setuptools zc.buildout setuptools-scm
  - buildout -nvv
script:
  - bin/test --cache-clear --cov-report term-missing --cov src
after_success:
cache:
  pip: true
  directories:
    - eggs/
notifications:
  webhooks:
    secure: DJrbGx2gA3rM9/LZ2guVHI/1wPfOoVRQ2iJMNs1NpsBSnkUO19iGwh2Ca3xhKyz8IGCVWkmHOPruWw5Eo74jaV7nuabyjMeIS8GxZh2jtL55dgsXSOg9LsjC+WoJivBdNL6QP7+Q10xrsLtVzI4TmI7Dhzk7/vLyaqCOldw2+mDMDeNauYCOOpf5WDP/9ERay17Noi1BDtDSgt9PPstQWpW05e49g4Yfh+g2uY7C366MRzsBnOdQaRFW3HhLgEmpRLcE4+1mPwqB7hsGLsqiF52M0Di0cZ2fUqRgeHw5RC3vuqe6JVyXodpziRa6dNu4mHrqzSV+RWxl+PzHqVQfB32+9wGque2kczhGMIA+6OGtNLhff18n8hBqpZu9lDkHebiHXJuOCR4/G1s3oRbVH70SaNJ4eM9XqbjArLDvv1GsyiBFFVzrxeGBAHUZ6huOTujFIzJEuS1deC6e4Cxn3uYEpBcivFrHkoMKOLfEVFeZycoylwBnz/qcAE1sz9OyLImMY2IIhVK4kIGUD3LnEydXqzPKm//LryNThrXl1Oxcp08AbloG0DwaqtaS/Qqmq1ooChgKoCurZaXx6oZsvE//Fvvc03QpXt9Q9mAagYmdpZmP9yayQQ9Cugt9ZCJneI05FfH697Xdw/DG8g9kID7lUzDS3YpM4itA4xDJalA=
